version: "3.7"

services:
  database:
    image: postgres
    container_name: database-ignite
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=ignite
    volumes:
      - pgdata:/data/postgres
    

  app: 
    build: .
    container_name: api-ignite
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local